-- Disable RLS on all tables so your website can read the data
ALTER TABLE shop_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_stage_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE designs DISABLE ROW LEVEL SECURITY;
ALTER TABLE gallery DISABLE ROW LEVEL SECURITY;
